---
title: "Project-3"
author: "Sarba"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Importing packages
library (tidyverse)
```


```{r}
# Importing datasets
data <- read_csv("/home/upretys/STA 518/Project/Project-3/worldometer_data.csv")
df <- read_csv("/home/upretys/STA 518/Project/Project-3/country_wise_latest.csv")
```
```{r}
# Renaming columns
data <- data %>%
  rename ("New cases" = "NewCases", "Total cases" = "TotalCases", "Total deaths" = "TotalDeaths", "New deaths" = "NewDeaths", "Total recovered" = "TotalRecovered", "New recovered" = "NewRecovered", "Active cases" = "ActiveCases", "Total tests" = "TotalTests")

```

```{r}
# Restructuring the dataset
data <- data %>%
  select(`Country/Region`:Population, `Tot Cases/1M pop`: `Total tests`)

```


```{r}
# Joining two datasets
j_data <- data %>%
  left_join(df, by = "Country/Region")
```

```{r}
# Dropping NAs
j_data <- j_data %>% 
  drop_na()
```


```{r}
# Top 10 countries with highest active cases
j_data  %>% 
  arrange(desc(Active)) %>% 
  head(10)
```

```{r}
# Top 10 countries with highest deaths
j_data  %>% 
  arrange(desc(Deaths)) %>% 
  head(10)
```

